import type { AnalyticalQuestion } from "../types";

export const ATTENDANCE_QUESTIONS: AnalyticalQuestion[] = [
  {
    id: "attendance.kpi.total_hours",
    text: "What are total hours worked?",
    intent: "kpi headline stat panel attendance total hours",
    verticals: ["attendance"],
    personas: ["manager", "executive"],
    basePriority: 8,
    kind: "kpi",
    requires: { measurePattern: /hours/i },
  },
  {
    id: "attendance.kpi.present",
    text: "How many employees present?",
    intent: "kpi headline stat panel attendance present count",
    verticals: ["attendance"],
    personas: ["manager", "operator"],
    basePriority: 8,
    kind: "kpi",
  },
  {
    id: "attendance.kpi.leave",
    text: "How many on leave?",
    intent: "kpi headline stat panel attendance leave count",
    verticals: ["attendance"],
    personas: ["manager", "executive"],
    basePriority: 7,
    kind: "kpi",
  },
  {
    id: "attendance.chart.hours_by_department",
    text: "Hours by department",
    intent: "hours bar chart by department with value labels",
    verticals: ["attendance"],
    personas: ["manager"],
    basePriority: 9,
    kind: "chart",
    dimensionKey: "department",
    matchPatterns: [/hours?\s*by\s*department|department\s*hours/i],
    requires: { dimensionPattern: /department/i, measurePattern: /hours/i },
  },
  {
    id: "attendance.chart.status",
    text: "Headcount by status",
    intent: "status breakdown bar chart with value labels",
    verticals: ["attendance"],
    personas: ["manager", "executive"],
    basePriority: 8,
    kind: "chart",
    dimensionKey: "status",
    matchPatterns: [/status|leave|present|breakdown/i],
    requires: { dimensionPattern: /status/i },
  },
  {
    id: "attendance.table.log",
    text: "Show attendance log",
    intent: "attendance timesheet table",
    verticals: ["attendance"],
    personas: ["analyst", "operator"],
    basePriority: 9,
    kind: "table",
    matchPatterns: [/attendance\s*table|show\s*employees|timesheet|all\s*rows/i],
  },
];
