import type { AnalyticalQuestion } from "../types";

export const LEDGER_QUESTIONS: AnalyticalQuestion[] = [
  {
    id: "ledger.kpi.balance",
    text: "What is current balance?",
    intent: "kpi headline stat panel ledger balance",
    verticals: ["ledger"],
    personas: ["executive", "manager"],
    basePriority: 9,
    kind: "kpi",
    requires: { measurePattern: /balance/i },
  },
  {
    id: "ledger.kpi.net_flow",
    text: "What is net cash flow?",
    intent: "kpi headline stat panel ledger net flow",
    verticals: ["ledger"],
    personas: ["executive"],
    basePriority: 8,
    kind: "kpi",
    requires: { measurePattern: /debit|credit|balance/i },
  },
  {
    id: "ledger.chart.balance_trend",
    text: "Balance over time",
    intent: "balance line chart over time monotone",
    verticals: ["ledger"],
    personas: ["executive", "manager"],
    basePriority: 9,
    kind: "chart",
    dimensionKey: "time",
    matchPatterns: [/balance.*time|trend|over\s*time/i],
    requires: { timeField: true, measurePattern: /balance/i },
  },
  {
    id: "ledger.chart.expenses",
    text: "Expenses by category",
    intent: "expense debit bar chart by category with value labels",
    verticals: ["ledger"],
    personas: ["manager"],
    basePriority: 8,
    kind: "chart",
    dimensionKey: "category",
    matchPatterns: [/expense|debit|spend/i],
    requires: { dimensionPattern: /category/i, measurePattern: /debit/i },
  },
  {
    id: "ledger.chart.revenue",
    text: "Revenue by category",
    intent: "revenue credit bar chart by category with value labels",
    verticals: ["ledger"],
    personas: ["manager", "executive"],
    basePriority: 8,
    kind: "chart",
    dimensionKey: "category",
    matchPatterns: [/revenue|credit|income/i],
    requires: { dimensionPattern: /category/i, measurePattern: /credit/i },
  },
  {
    id: "ledger.chart.payment_method",
    text: "Volume by payment method",
    intent: "payment method volume bar chart with value labels",
    verticals: ["ledger"],
    personas: ["analyst", "manager"],
    basePriority: 7,
    kind: "chart",
    dimensionKey: "payment_method",
    matchPatterns: [/payment\s*method|pay\s*method/i],
    requires: { dimensionPattern: /payment\s*method/i },
  },
  {
    id: "ledger.chart.waterfall",
    text: "Net flow waterfall by category",
    intent: "ledger category waterfall bridge variance",
    verticals: ["ledger"],
    personas: ["executive", "analyst"],
    basePriority: 7,
    kind: "chart",
    matchPatterns: [/waterfall|bridge|variance|walk/i],
    requires: { dimensionPattern: /category/i },
  },
  {
    id: "ledger.table.transactions",
    text: "Show all transactions",
    intent: "ledger transaction table",
    verticals: ["ledger"],
    personas: ["analyst"],
    basePriority: 9,
    kind: "table",
    matchPatterns: [/transaction\s*table|show\s*transactions|ledger\s*table|all\s*rows/i],
  },
];
