import { describe, expect, it } from "vitest";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  runCompositionSimulations,
  summarizeSimulations,
  type SimulationResult,
} from "./compositionSimulation";

function toMarkdownTable(results: SimulationResult[]): string {
  const header =
    "| ID | Category | Scenario | Outcome | RFC | Details |\n|----|----------|----------|---------|-----|---------|";
  const rows = results.map(
    (r) =>
      `| ${r.id} | ${r.category} | ${r.description} | **${r.outcome}** | ${r.rfcRecommendation} | ${r.details.replace(/\|/g, "\\|")} |`,
  );
  return [header, ...rows].join("\n");
}

describe("composition simulation (RFC-002 feasibility)", () => {
  const results = runCompositionSimulations();
  const summary = summarizeSimulations(results);

  it("runs all scenarios", () => {
    expect(results.length).toBeGreaterThanOrEqual(20);
  });

  it("canonical combos work today", () => {
    for (const id of ["S01", "S04", "S05"]) {
      const r = results.find((x) => x.id === id)!;
      expect(r.outcome, `${id}: ${r.details}`).toBe("works");
    }
  });

  it("documents C136 validation gates", () => {
    const results = runCompositionSimulations();
    const mustError = ["S11", "S12", "S13", "S14", "S15", "S18", "S19"];
    for (const id of mustError) {
      const r = results.find((x) => x.id === id)!;
      expect(r.outcome, `${id}: ${r.details}`).toBe("throws");
    }
    for (const id of ["S01", "S04", "S05", "S16", "S17"]) {
      const r = results.find((x) => x.id === id)!;
      expect(r.outcome, `${id}: ${r.details}`).toBe("works");
    }
  });

  it("writes simulation report for Dashboarder RFC-002", () => {
    const dashboarderPath = resolve(
      import.meta.dirname,
      "../../../../Dashboarder/docs/charts/rfcs/RFC-002-composition-simulation.md",
    );
    const body = `# RFC-002 composition simulation results

> Generated by \`@axicharts/charts-spec\` — \`compositionSimulation.test.ts\`  
> Run: \`pnpm --filter @axicharts/charts-spec test compositionSimulation\`

## Summary (${new Date().toISOString().slice(0, 10)})

| Outcome | Count |
|---------|-------|
| works | ${summary.works} |
| silent_bad | ${summary.silent_bad} |
| ignored | ${summary.ignored} |
| throws | ${summary.throws} |

**Engine under test:** C135 \`type: "blocks"\` → \`blockMarksToChartProps\` → \`compilePanel\` → \`ComboChart\`.

## Full results

${toMarkdownTable(results)}

## Gaps (need C136 validator)

${summary.gaps
  .map((r) => `- **${r.id}** (${r.description}): today \`${r.outcome}\` → RFC \`${r.rfcRecommendation}\``)
  .join("\n")}
`;
    writeFileSync(dashboarderPath, body, "utf8");
    expect(summary.gaps.length).toBeGreaterThan(0);
  });
});
