import type { AnalyticalQuestion } from "../types";

export const SALES_QUESTIONS: AnalyticalQuestion[] = [
  {
    id: "sales.kpi.total_pipeline",
    text: "What is total pipeline value?",
    intent: "kpi headline stat panel sales pipeline total",
    verticals: ["sales"],
    personas: ["executive", "manager"],
    basePriority: 8,
    kind: "kpi",
  },
  {
    id: "sales.kpi.weighted_forecast",
    text: "What is weighted forecast?",
    intent: "kpi headline stat panel sales weighted forecast",
    verticals: ["sales"],
    personas: ["executive"],
    basePriority: 10,
    kind: "kpi",
  },
  {
    id: "sales.kpi.closed_won",
    text: "How much closed won?",
    intent: "kpi headline stat panel sales closed won",
    verticals: ["sales"],
    personas: ["executive", "manager"],
    basePriority: 7,
    kind: "kpi",
  },
  {
    id: "sales.kpi.open_deals",
    text: "How many open deals?",
    intent: "kpi headline stat panel sales open deals",
    verticals: ["sales"],
    personas: ["manager", "analyst"],
    basePriority: 7,
    kind: "kpi",
  },
  {
    id: "sales.chart.by_stage",
    text: "Pipeline value by stage",
    intent: "pipeline value bar chart by stage with value labels",
    verticals: ["sales"],
    personas: ["manager", "executive"],
    basePriority: 9,
    kind: "chart",
    dimensionKey: "stage",
    matchPatterns: [/by\s*stage|funnel|pipeline\s*stage/i],
    requires: { dimensionPattern: /stage|phase/i, measurePattern: /value|amount/i },
  },
  {
    id: "sales.chart.open_by_stage",
    text: "Open pipeline by stage",
    intent: "open pipeline value bar chart by stage with value labels",
    verticals: ["sales"],
    personas: ["manager", "analyst"],
    basePriority: 8,
    kind: "chart",
    dimensionKey: "stage",
    matchPatterns: [/open.*stage|stage.*open/i],
    requires: { dimensionPattern: /stage|phase/i, measurePattern: /value|amount/i },
  },
  {
    id: "sales.chart.weighted_forecast",
    text: "Weighted forecast by salesperson",
    intent: "weighted forecast bar chart by salesperson with value labels",
    verticals: ["sales"],
    personas: ["executive", "manager"],
    basePriority: 10,
    kind: "chart",
    dimensionKey: "salesperson",
    matchPatterns: [/weighted|forecast/i],
    requires: {
      dimensionPattern: /salesperson|rep|owner/i,
      measurePattern: /value|amount|probability/i,
    },
  },
  {
    id: "sales.chart.by_salesperson",
    text: "Pipeline value by salesperson",
    intent: "pipeline value bar chart by salesperson with value labels",
    verticals: ["sales"],
    personas: ["manager"],
    basePriority: 8,
    kind: "chart",
    dimensionKey: "salesperson",
    matchPatterns: [/salesperson|by\s*rep|by\s*owner/i],
    requires: {
      dimensionPattern: /salesperson|rep|owner/i,
      measurePattern: /value|amount/i,
    },
  },
  {
    id: "sales.chart.by_source",
    text: "Pipeline value by lead source",
    intent: "pipeline value bar chart by source with value labels",
    verticals: ["sales"],
    personas: ["analyst", "manager"],
    basePriority: 6,
    kind: "chart",
    dimensionKey: "source",
    matchPatterns: [/source|channel|lead\s*source/i],
    requires: { dimensionPattern: /source|channel/i, measurePattern: /value|amount/i },
  },
  {
    id: "sales.table.opportunities",
    text: "Show all opportunities",
    intent: "pipeline opportunities table",
    verticals: ["sales"],
    personas: ["analyst", "manager"],
    basePriority: 8,
    kind: "table",
    matchPatterns: [/pipeline\s*table|opportunities|show\s*deals|all\s*rows/i],
  },
];
